version: '3'
services:
  webserver:
    build: ./docker/node
    image: nuxt_image
    container_name: nuxt_container
    tty: true
    volumes:
      - ./data:/app
    ports:
      - "3000:3000"
      - "9005:9005"
